blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PostCreateView, PostDeleteView, PostDetailView, PostListView, PostUpdateView

app_name = BlogConfig.name


urlpatterns = [
    path("posts/", PostListView.as_view(), name="posts"),
    path("post/<int:pk>", PostDetailView.as_view(), name="post"),
    path("post_update/<int:pk>", PostUpdateView.as_view(), name="post_update"),
    path("post_add/", PostCreateView.as_view(), name="post_add"),
    path("post_del/<int:pk>", PostDeleteView.as_view(), name="post_del"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (
    ContactCreateView,
    ProductCreateView,
    ProductDeleteView,
    ProductDetailView,
    ProductListView,
    ProductPublishView,
    ProductUnpublishView,
    ProductUpdateView, ProductsByCategoryView,
)

app_name = CatalogConfig.name


urlpatterns = [
    path("contacts/", ContactCreateView.as_view(), name="contacts"),
    path("products_list/", ProductListView.as_view(), name="products_list"),
    path("product/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path("product_update/<int:pk>", ProductUpdateView.as_view(), name="product_update"),
    path("product_add/", ProductCreateView.as_view(), name="product_add"),
    path("product_del/<int:pk>", ProductDeleteView.as_view(), name="product_del"),
    path("product/<int:pk>/publish/", ProductPublishView.as_view(), name="product_publish"),
    path("product/<int:pk>/unpublish/", ProductUnpublishView.as_view(), name="product_unpublish"),
    path('products_by_category/', ProductsByCategoryView.as_view(), name='products_by_category'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserRegisterView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/user_login.html"), name="user_login"),
    path(
        "logout/",
        LogoutView.as_view(template_name="users/user_logout.html", next_page="/catalog/products_list/"),
        name="user_logout",
    ),
    path("register/", UserRegisterView.as_view(template_name="users/user_register.html"), name="user_register"),
    path("email-confirm/<str:token>", email_verification, name="email-confirm"),
]

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=150, verbose_name="Заголовок")
    content = models.TextField(blank=True, null=True, verbose_name="Содержимое")
    image = models.ImageField(upload_to="blog/images", blank=True, null=True, verbose_name="Изображение")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания")
    sign = models.BooleanField(verbose_name="Признак публикации")
    views_cnt = models.IntegerField(default="0", verbose_name="Количество просмотров")

    def __str__(self):
        return f"Пост:{self.title} | Дата: {self.created_at} | Просмотров: {self.views_cnt}"

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["title", "created_at", "views_cnt"]

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from blog.models import Post


class PostListView(ListView):
    model = Post
    context_object_name = "posts"
    template_name = "blog/posts.html"

    def get_queryset(self):
        return Post.objects.filter(sign=True).order_by("created_at")


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"
    template_name = "blog/post.html"

    def get_object(self):
        post = Post.objects.get(pk=self.kwargs["pk"])
        post.views_cnt += 1
        post.save()
        return post


class PostCreateView(CreateView):
    model = Post
    fields = ["title", "content", "image", "sign"]
    template_name = "blog/post_add.html"
    success_url = reverse_lazy("blog:posts")


class PostUpdateView(UpdateView):
    model = Post
    fields = ["title", "content", "image", "sign"]
    template_name = "blog/post_update.html"

    def get_success_url(self):
        return reverse_lazy("blog:post", kwargs={"pk": self.object.pk})


class PostDeleteView(DeleteView):
    model = Post
    template_name = "blog/post_del.html"
    success_url = reverse_lazy("blog:posts")

blog/templates/blog/includes/ink_menu.html
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4"><h4>SkyStories</h4>
                <p class="text-body-secondary">Статьи по технологиям</p></div>
            <div class="col-sm-4 offset-md-1 py-4"><h4>Меню</h4>
              <ul class="list-unstyled">
                    <li><a href="{% url 'catalog:products_list' %}" class="text-white">Главная</a></li>
                    <li><a href="{% url 'catalog:contacts' %}" class="text-white">Контакты</a></li>
                    {% if user.is_authenticated %}
                    <li style="margin: 0px 20;">
                        <form action="{% url 'users:user_logout' %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link text-white p-0">Выйти</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'users:user_login' %}" class="text-white">Вход</a></li>
                    <li><a href="{% url 'users:user_register' %}" class="text-white">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container"><a href="#" class="navbar-brand d-flex align-items-center"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
    </div>
</div>