blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PostCreateView, PostDeleteView, PostDetailView, PostListView, PostUpdateView

app_name = BlogConfig.name


urlpatterns = [
    path("posts/", PostListView.as_view(), name="posts"),
    path("post/<int:pk>", PostDetailView.as_view(), name="post"),
    path("post_update/<int:pk>", PostUpdateView.as_view(), name="post_update"),
    path("post_add/", PostCreateView.as_view(), name="post_add"),
    path("post_del/<int:pk>", PostDeleteView.as_view(), name="post_del"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=150, verbose_name="Заголовок")
    content = models.TextField(blank=True, null=True, verbose_name="Содержимое")
    image = models.ImageField(upload_to="blog/images", blank=True, null=True, verbose_name="Изображение")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания")
    sign = models.BooleanField(verbose_name="Признак публикации")
    views_cnt = models.IntegerField(default="0", verbose_name="Количество просмотров")

    def __str__(self):
        return f"Пост:{self.title} | Дата: {self.created_at} | Просмотров: {self.views_cnt}"

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["title", "created_at", "views_cnt"]

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from blog.models import Post


class PostListView(ListView):
    model = Post
    context_object_name = "posts"
    template_name = "blog/posts.html"

    def get_queryset(self):
        return Post.objects.filter(sign=True).order_by("created_at")


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"
    template_name = "blog/post.html"

    def get_object(self):
        post = Post.objects.get(pk=self.kwargs["pk"])
        post.views_cnt += 1
        post.save()
        return post


class PostCreateView(CreateView):
    model = Post
    fields = ["title", "content", "image", "sign"]
    template_name = "blog/post_add.html"
    success_url = reverse_lazy("blog:posts")


class PostUpdateView(UpdateView):
    model = Post
    fields = ["title", "content", "image", "sign"]
    template_name = "blog/post_update.html"

    def get_success_url(self):
        return reverse_lazy("blog:post", kwargs={"pk": self.object.pk})


class PostDeleteView(DeleteView):
    model = Post
    template_name = "blog/post_del.html"
    success_url = reverse_lazy("blog:posts")

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Base_Template{% endblock %}</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">
    <script src="{% static 'js/color-modes.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        .bd-placeholder-img{font-size:1.125rem;text-anchor:middle;-webkit-user-select:none;-moz-user-select:none;user-select:none}@media (min-width: 768px){.bd-placeholder-img-lg{font-size:3.5rem}}.b-example-divider{width:100%;height:3rem;background-color:#0000001a;border:solid rgba(0,0,0,.15);border-width:1px 0;box-shadow:inset 0 .5em 1.5em #0000001a,inset 0 .125em .5em #00000026}.b-example-vr{flex-shrink:0;width:1.5rem;height:100vh}.bi{vertical-align:-.125em;fill:currentColor}.nav-scroller{position:relative;z-index:2;height:2.75rem;overflow-y:hidden}.nav-scroller .nav{display:flex;flex-wrap:nowrap;padding-bottom:1rem;margin-top:-1px;overflow-x:auto;text-align:center;white-space:nowrap;-webkit-overflow-scrolling:touch}.btn-bd-primary{--bd-violet-bg: #712cf9;--bd-violet-rgb: 112.520718, 44.062154, 249.437846;--bs-btn-font-weight: 600;--bs-btn-color: var(--bs-white);--bs-btn-bg: var(--bd-violet-bg);--bs-btn-border-color: var(--bd-violet-bg);--bs-btn-hover-color: var(--bs-white);--bs-btn-hover-bg: #6528e0;--bs-btn-hover-border-color: #6528e0;--bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);--bs-btn-active-color: var(--bs-btn-hover-color);--bs-btn-active-bg: #5a23c8;--bs-btn-active-border-color: #5a23c8}.bd-mode-toggle{z-index:1500}.bd-mode-toggle .bi{width:1em;height:1em}.bd-mode-toggle .dropdown-menu .active .bi{display:block!important}
    </style>
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
    </symbol>
</svg>
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" aria-hidden="true">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span></button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>
<header data-bs-theme="dark">
{% include 'blog/includes/ink_menu.html' %}
</header>
<main>
    {% block content %}
    {% endblock %}
</main>
<footer class="text-body-secondary py-5">
    <div class="container"><p class="float-end mb-1"><a href="#">Наверх</a></p>
        <p class="mb-0">Сайт разработан совместно со <a href="https://my.sky.pro/">SkyPro</a> Романенко Антоном</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" class="astro-vvvwv3sm"></script>
</body>
</html>

blog/templates/blog/post.html
{% extends 'blog/base.html' %}
{% load my_tags_blog %}
{% block title %}{{ post.name }}{% endblock %}
{% block content %}
<section class="py-5 text-center container">
        <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">{{ post.title }}</h1>
        <p class="lead text-body-secondary">Пост № {{ post.pk }}</p>
        <p>
            <a href="{% url 'blog:post_update' post.pk %}" class="btn btn-primary my-2">Редактировать</a>
            <a href="{% url 'blog:post_del' post.pk %}" class="btn btn-secondary my-2">Удаление</a>
        </p>
    </div>
</div>
    </section>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ post.image | media_filter }}">
                    <div class="card-body">
                        <h1 class="card-title">{{ post.title }}</h1>
                        <p class="card-text">Контент: {{ post.content }}</p>
                        <p class="card-text">Дата создания: {{ post.created_at }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blog:posts' %}" role="button">Назад</a>
                            </div>
                            <small class="text-body-secondary">Просмотры: {{ post.views_cnt }}</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_add.html
{% extends 'blog/base.html' %}
{% load my_tags_blog %}
{% block title %}Новый пост{% endblock %}
{% block content %}
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Новый пост</h1></div>
  </div>
</section>
<div class="d-flex justify-content-center">
  <div class="col-lg-3 col-md-6 col-sm-12">
      <div class="card mb-4 box-shadow">
          <div class="card-header text-center">
              <h4 class="my-0 font-weight-normal">Напишите свою статью</h4>
          </div>
          <div class="card-body">
              <form method="post" action="" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Добавить</button>
                  <a href="{% url 'blog:posts' %}" class="btn btn-danger" type="button">Назад</a>
              </form>
          </div>
      </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_del.html
{% extends 'blog/base.html' %}
{% load my_tags_blog %}
{% block title %}Удаление{% endblock %}
{% block content %}
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Удаление</h1></div>
  </div>
</section>
<div class="d-flex justify-content-center">
  <div class="col-lg-3 col-md-6 col-sm-12">
      <div class="card mb-4 box-shadow">
          <div class="card-header text-center">
              <h4 class="my-0 font-weight-normal">Удаление поста из блога</h4>
          </div>
          <div class="card-body">
              <form method="post" action="" enctype="multipart/form-data">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Удалить</button>
                  <a href="{% url 'blog:posts' %}" class="btn btn-danger" type="button">Назад</a>
              </form>
          </div>
      </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_update.html
{% extends 'blog/base.html' %}
{% load my_tags_blog %}
{% block title %}Радактирование{% endblock %}
{% block content %}
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Радактирование</h1></div>
  </div>
</section>
<div class="d-flex justify-content-center">
  <div class="col-lg-3 col-md-6 col-sm-12">
      <div class="card mb-4 box-shadow">
          <div class="card-header text-center">
              <h4 class="my-0 font-weight-normal">Внесите изменения</h4>
          </div>
          <div class="card-body">
              <form method="post" action="" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Сохранить</button>
                  <a href="{% url 'blog:posts' %}" class="btn btn-danger" type="button">Назад</a>
              </form>
          </div>
      </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/posts.html
{% extends 'blog/base.html' %}
{% load my_tags_blog %}
{% block title %}Все посты{% endblock %}
{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Посты</h1>
        <p class="lead text-body-secondary">Вы можете ознакомиться с постами нашего блог-сайта</p>
        <p>
            <a href="{% url 'blog:post_add' %}" class="btn btn-primary my-2">Запостить</a>
        </p>
    </div>
</div>
</section>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for post in posts %}
            <div class="col">
                <div class="card shadow-sm">
                    <img height="300" src="{{ post.image | media_filter }}" style="width: 100% height: auto object-fit: contain" alt="Картинка товара">
                    <div class="card-body">
                        <p class="card-text">Наименование: {{ post.title }}</p>
                        <p class="card-text">Просмотры: {{ post.views_cnt }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blog:post' post.pk %}" role="button">Посмотреть</a>
                            </div>
                            <small class="text-body-secondary">{{ post.created_at }}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}